[workspace]
members = [
    "examples",
    "gobs-egui",
    "gobs-game",
    "gobs-render",
    "gobs-scene",
    "gobs-utils",
]
resolver = "2"

[workspace.package]
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
bitflags = "2"
bytemuck = { version = "1.14", features = ["derive"] }
eframe = { version = "0.23" }
egui = { version = "0.23" }
egui_extras = { version = "0.23", features = ["image"] }
fs_extra = "1.3"
glam = { version = "0.24", features = ["bytemuck"] }
image = "0.24"
itertools = { version = "0.11" }
log = "0.4"
naga = { version = "0.14" }
pollster = "0.3"
rusttype = "0.9"
simplelog = "0.12"
time = "0.3"
tobj = { version = "4.0.0", features = ["async"] }
unicode-normalization = "0.1"
uuid = { version = "1.3", features = ["v4"] }
winit = "0.28"
wgpu = "0.18"
