[workspace]
members = [
    "examples",
    "gobs-core",
    "gobs-egui",
    "gobs-game",
    "gobs-material",
    "gobs-ray",
    "gobs-render",
    "gobs-scene",
    "gobs-utils",
    "gobs",
]
resolver = "2"

[workspace.package]
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2021"
version = "0.1.0"

[workspace.dependencies.gobs]
package = "gobs"
path = "./gobs"

[workspace.dependencies.gobs-core]
package = "gobs-core"
path = "./gobs-core"

[workspace.dependencies.gobs-egui]
package = "gobs-egui"
path = "./gobs-egui"

[workspace.dependencies.gobs-game]
package = "gobs-game"
path = "./gobs-game"

[workspace.dependencies.gobs-material]
package = "gobs-material"
path = "./gobs-material"

[workspace.dependencies.gobs-ray]
package = "gobs-ray"
path = "./gobs-ray"

[workspace.dependencies.gobs-render]
package = "gobs-render"
path = "./gobs-render"

[workspace.dependencies.gobs-scene]
package = "gobs-scene"
path = "./gobs-scene"

[workspace.dependencies.gobs-utils]
package = "gobs-utils"
path = "./gobs-utils"

[workspace.dependencies]
anyhow = "1.0"
bitflags = "2"
bytemuck = { version = "1.14", features = ["derive"] }
egui = { version = "0.25", features = ["bytemuck"]}
fs_extra = "1.3"
glam = { version = "0.24", features = ["bytemuck"] }
image = "0.24"
indexmap = "2.1.0"
itertools = { version = "0.12" }
log = "0.4"
naga = { version = "0.14" }
pollster = "0.3"
rand = "0.8"
rayon = "1.8"
rusttype = "0.9"
simplelog = "0.12"
time = "0.3"
tobj = { version = "4.0.0", features = ["async"] }
unicode-normalization = "0.1"
uuid = { version = "1.3", features = ["v4"] }
winit = "0.28"
wgpu = "0.18"
