[workspace]
members = [
    "examples",
    "gobs-game",
    "gobs-vulkan",
    "gobs-utils",
]
resolver = "2"

[workspace.package]
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2021"
version = "0.1.0"

[workspace.dependencies.gobs]
package = "gobs"
path = "./gobs"

[workspace.dependencies.gobs-game]
package = "gobs-game"
path = "./gobs-game"

[workspace.dependencies.gobs-utils]
package = "gobs-utils"
path = "./gobs-utils"

[workspace.dependencies]
ash = { version = "0.37", features = ["linked", "debug"] }
ash-window = "0.12"
anyhow = "1.0"
bitflags = "2"
bytemuck = { version = "1.14", features = ["derive"] }
egui = { version = "0.24", features = ["bytemuck"]}
fs_extra = "1.3"
glam = { version = "0.25", features = ["bytemuck"] }
image = "0.24"
indexmap = "2.1.0"
itertools = { version = "0.12" }
log = "0.4"
pollster = "0.3"
rand = "0.8"
raw-window-handle = "0.5"
simplelog = "0.12"
time = "0.3"
uuid = { version = "1.3", features = ["v4"] }
winit = "0.28"
