[package]
name = "gobs-render"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "gobs_render"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
simplelog = { workspace = true }
uuid = { workspace = true }
winit = { workspace = true }
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
gobs-vulkan = {path = "../gobs-vulkan"}