[package]
name = "gobs-render"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
glam = { workspace = true }
gobs-core = { workspace = true }
gobs-gfx = { workspace = true }
gobs-gfx-vulkan = { workspace = true, optional = true}
gobs-resource = { workspace = true }
image = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
winit = { workspace = true }

[features]
default = ["vulkan"]
vulkan = ["dep:gobs-gfx-vulkan"]
