[package]
name = "gobs-render"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[lib]
name = "gobs_render"
path = "src/lib.rs"

[dependencies]
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
vulkano = "0.13"
vulkano-shaders = "0.13"
vulkano-win = "0.13"
winit = "0.19"
cgmath = "0.17"
log = "0.4"
time = "0.1"
uuid = { version = "0.7", features = ["v4"] }
