[package]
name = "gobs-render"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2018"

[lib]
name = "gobs_render"
path = "src/lib.rs"

[dependencies]
log = "0.4"
simplelog = "0.8"
uuid = { version = "0.7", features = ["v4"] }
winit = "0.22"
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
gobs-vulkan = {path = "../gobs-vulkan"}