[package]
name = "gobs-render"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
gobs-vulkan = { workspace = true }
gpu-allocator = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
winit = { workspace = true }
