[package]
name = "gobs-render"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[lib]
name = "gobs_render"
path = "src/lib.rs"

[dependencies]
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
vulkano = {path = "../../../vulkano/vulkano", version="0.10"}
vulkano-shader-derive = {path = "../../../vulkano/vulkano-shader-derive", version="0.10"}
vulkano-win = {path = "../../../vulkano/vulkano-win", version="0.10"}
winit = "0.17"
cgmath = "0.16"
log = "0.4"
time = "0.1"
uuid = { version = "0.6", features = ["v4"] }
