[package]
name = "gobs-utils"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2018"

[lib]
name = "gobs_utils"
path = "src/lib.rs"

[dependencies]
cgmath = "0.17"
time = "0.1"
