[package]
name = "gobs-utils"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "gobs_utils"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
time = { workspace = true }
