[package]
name = "gobs-gfx-vulkan"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
gobs-core = { workspace = true }
gobs-gfx = { workspace = true }
gobs-resource = { workspace = true }
gobs-vulkan = { workspace = true }
gpu-allocator = { workspace = true }
image = { workspace = true }
indexmap = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
winit = { workspace = true }
