[package]
name = "gobs-gfx"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
futures = { workspace = true }
glam = { workspace = true }
gobs-core = { workspace = true }
gobs-utils = { workspace = true }
gobs-vulkan = { workspace = true }
gpu-allocator = { workspace = true }
image = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
winit = { workspace = true }

[features]
default = ["vulkan"]
vulkan = []
