[package]
name = "gobs-gfx"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
gobs-vulkan = { workspace = true }
image = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
winit = { workspace = true }
