[package]
name = "examples"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
egui = { workspace = true }
egui_extras = { workspace = true }
glam = { workspace = true }
gobs = { workspace = true }
pollster = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tracy = { workspace = true }

[build-dependencies]
fs_extra = { workspace = true }
tracing = { workspace = true }
gobs-build = { workspace = true }
