[package]
name = "examples"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
egui = { workspace = true }
glam = { workspace = true }
gobs = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
fs_extra = { workspace = true }
