[package]
name = "examples"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
glam = { workspace = true }
gobs = { workspace = true }
gpu-allocator = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

[build-dependencies]
naga = { workspace = true }