[package]
name = "examples"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[dependencies]
gobs-render = {path = "../gobs-render"}
gobs-scene = {path = "../gobs-scene"}
gobs-game = {path = "../gobs-game"}
gobs-utils = {path = "../gobs-utils"}
cgmath = "0.16"
image = "0.18"
log = "0.4"
simplelog = "0.5"
