[package]
name = "examples"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2018"

[build-dependencies]
glsl-to-spirv = "0.1.6"

[dependencies]
gobs-game = {path = "../gobs-game"}
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
gobs-render = {path = "../gobs-render"}
cgmath = "0.17"
image = "0.23"
log = "0.4"
simplelog = "0.5"
time = "0.1"
winit = "0.22"
