[package]
name = "examples"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
gobs-game = { path = "../gobs-game" }
gobs-scene = { path = "../gobs-scene" }
gobs-utils = { path = "../gobs-utils" }
gobs-wgpu = { path = "../gobs-wgpu" }
glam = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
uuid = { workspace = true }
