[package]
name = "examples"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[build-dependencies]
glsl-to-spirv = "0.1.6"

[dependencies]
gobs-render = {path = "../gobs-render"}
gobs-scene = {path = "../gobs-scene"}
gobs-game = {path = "../gobs-game"}
gobs-utils = {path = "../gobs-utils"}
gobs-vulkan = {path = "../gobs-vulkan"}
cgmath = "0.16"
image = "0.18"
log = "0.4"
simplelog = "0.5"
time = "0.1"
winit = "0.18"
