[package]
name = "examples"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
glam = { workspace = true }
gobs = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }

[build-dependencies]
naga = { workspace = true }