[package]
name = "gobs-core"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
gobs-utils = { path = "../gobs-utils" }
image = { workspace = true }
indexmap = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
