[package]
name = "gobs-core"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bitflags = { workspace = true }
bytemuck = { workspace = true }
gobs-utils = { workspace = true }
image = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
