[package]
name = "gobs-vulkan"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[lib]
name = "gobs_vulkan"
path = "src/lib.rs"

[dependencies]
ash = "0.26"
log = "0.4"
simplelog = "0.5"
timer = "0.1"
uuid = { version = "0.6", features = ["v4"] }
winit = "0.18"
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
