[package]
name = "gobs-material"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
gobs-core = { workspace = true }
gobs-utils = { workspace = true }
glam = { workspace = true }
image = { workspace = true }
log = { workspace = true }
naga = { workspace = true }
pollster = { workspace = true }
simplelog = { workspace = true }
uuid = { workspace = true }
wgpu = { workspace = true }

[build-dependencies]
fs_extra = { workspace = true }
