[package]
name = "gobs-egui"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true }
gobs-core = { path = "../gobs-core" }
gobs-game = { path = "../gobs-game" }
gobs-render = { path = "../gobs-render" }
log = { workspace = true }
egui = { workspace = true }
glam = { workspace = true }
pollster = { workspace = true }
