[package]
name = "gobs-game"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
simplelog = { workspace = true }
winit = { workspace = true }
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
gobs-render = {path = "../gobs-render"}
