[package]
name = "gobs-game"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[dependencies]
gobs-render = {path = "../gobs-render"}
winit = "0.11.2"
cgmath = "0.16"
time = "0.1"
image = "0.18"
