[package]
name = "gobs-game"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
gobs-scene = { path = "../gobs-scene" }
gobs-utils = { path = "../gobs-utils" }
log = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
