[package]
name = "gobs-game"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17"
log = "0.4"
simplelog = "0.8"
winit = "0.22"
gobs-scene = {path = "../gobs-scene"}
gobs-utils = {path = "../gobs-utils"}
gobs-vulkan = {path = "../gobs-vulkan"}
