[package]
name = "gobs-game"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[dependencies]
gobs-render = {path = "../gobs-render"}
gobs-scene = {path = "../gobs-scene"}
cgmath = "0.16"
winit = "0.18"
