[package]
name = "gobs-scene"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "gobs_scene"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
gobs-core = { workspace = true }
gobs-material = { workspace = true }
gobs-utils = { workspace = true }
gobs-render = { workspace = true }
image = { workspace = true }
log = { workspace = true }
tobj = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
fs_extra = { workspace = true }
