[package]
name = "gobs-scene"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]

[lib]
name = "gobs_scene"
path = "src/lib.rs"

[dependencies]
cgmath = "0.17"
image = "0.21"
unicode-normalization = "0.1"
rusttype = "0.5.2"
uuid = { version = "0.7", features = ["v4"] }
