[package]
name = "gobs-scene"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
glam = { workspace = true }
gltf = { workspace = true }
gobs-core = { workspace = true }
gobs-utils = { workspace = true }
gobs-render = { workspace = true }
gobs-vulkan = { workspace = true }
gpu-allocator = { workspace = true }
log = { workspace = true }
