[package]
name = "gobs-scene"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "gobs_scene"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
cgmath = { workspace = true }
image = { workspace = true }
unicode-normalization = { workspace = true }
rusttype = { workspace = true }
uuid = { workspace = true }
