[package]
name = "gobs-scene"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[lib]
name = "gobs_scene"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }
gobs-utils = { path = "../gobs-utils" }
gobs-wgpu = { path = "../gobs-wgpu" }
image = { workspace = true }
log = { workspace = true }
tobj = { workspace = true }
uuid = { workspace = true }
wgpu = { workspace = true }
