[package]
name = "gobs-scene"
version = "0.1.0"
authors = ["franckv <franck.vdl@gmail.com>"]
edition = "2018"

[lib]
name = "gobs_scene"
path = "src/lib.rs"

[dependencies]
cgmath = "0.18"
image = "0.23"
unicode-normalization = "0.1"
rusttype = "0.9"
uuid = { version = "0.7", features = ["v4"] }
